moduledir '/etc/puppetlabs/code/modules/'

mod 'puppetlabs-apt', '7.4.1'
mod 'puppetlabs-stdlib', '6.3.0'
mod 'puppetlabs-concat', '6.2.0'
mod 'puppet-openvpn', '8.2.0'
mod 'puppetlabs-firewall', '2.3.0'
mod 'theforeman-dns', '7.0.0'
mod 'puppetlabs-translate', '2.2.0'
mod 'thias-sysctl', '1.0.6'
